--- #YAML:1.0
name:               Lingua-Lid
version:            0.04
abstract:           Interface to the language and encoding identifier "lid"
author:
    - Alex Linke <alinke@lingua-systems.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
